// Hand-written (not generated by scripts/sync-pvp-engine.mjs — same as cors.ts in this
// directory): shared between pvp-turn-start and pvp-turn-act's cleanup path and pvp-turn-act's
// finish path. Elo math and the resolve_pvp_attack RPC are byte-for-byte what the old
// pvp-attack Edge Function used — only the battle *resolution* mechanics changed, not how a
// finished battle's outcome gets committed.

const K_FACTOR = 32;
const REWARD_CREDITS_WIN = 30;
const REWARD_CREDITS_LOSS = 5;
/** XP the winning side's fielded characters earn — see pvp-attack's old identical constant for why both a win and a repelled attack pay XP (only the defender, on a loss). */
const PVP_XP_WIN = 25;

function expectedScore(a: number, b: number): number {
  return 1 / (1 + 10 ** ((b - a) / 400));
}

export interface CommitBattleOutcomeParams {
  attackerId: string;
  defenderId: string;
  won: boolean;
  attackerRating: number;
  defenderRating: number;
  // deno-lint-ignore no-explicit-any
  log: any;
  attackerCharacterIds: string[];
  defenderCharacterIds: string[];
}

export interface CommitBattleOutcomeResult {
  won: boolean;
  ratingDelta: number;
  newRating: number;
  rewardCredits: number;
  xpEarnedByCharacterId: Record<string, number>;
}

/**
 * Commits a finished turn-based PvP battle: Elo rating via the existing resolve_pvp_attack RPC
 * (service-role only, migration 0020 — unchanged) + XP for the winning side's fielded
 * characters. `admin` must be a service-role client — this writes to another player's rows.
 */
// deno-lint-ignore no-explicit-any
export async function commitBattleOutcome(admin: any, params: CommitBattleOutcomeParams): Promise<CommitBattleOutcomeResult> {
  const { attackerId, defenderId, won, attackerRating, defenderRating, log, attackerCharacterIds, defenderCharacterIds } = params;

  const expected = expectedScore(attackerRating, defenderRating);
  const attackerDelta = Math.round(K_FACTOR * ((won ? 1 : 0) - expected));
  const defenderDelta = -attackerDelta;
  const newRating = Math.max(0, attackerRating + attackerDelta);

  const { error: rpcError } = await admin.rpc('resolve_pvp_attack', {
    p_attacker_id: attackerId,
    p_defender_id: defenderId,
    p_winner: won ? 'attacker' : 'defender',
    p_log: log,
    p_attacker_rating_delta: attackerDelta,
    p_defender_rating_delta: defenderDelta,
  });
  if (rpcError) throw new Error(rpcError.message);

  const xpWinnerIds = won ? attackerCharacterIds : defenderCharacterIds;
  const xpWinnerUserId = won ? attackerId : defenderId;
  const xpEarnedByCharacterId: Record<string, number> = {};
  if (xpWinnerIds.length > 0) {
    const { data: winnerRows } = await admin
      .from('player_characters')
      .select('character_id, xp, rarity')
      .eq('user_id', xpWinnerUserId)
      .in('character_id', xpWinnerIds);
    // A defender may have sold or never owned a character still named in their saved snapshot;
    // only rows that actually exist are paid.
    const rows = winnerRows ?? [];
    if (rows.length > 0) {
      await admin.from('player_characters').upsert(
        // deno-lint-ignore no-explicit-any
        rows.map((c: any) => ({ user_id: xpWinnerUserId, character_id: c.character_id, xp: c.xp + PVP_XP_WIN, rarity: c.rarity })),
        { onConflict: 'user_id,character_id' },
      );
      // deno-lint-ignore no-explicit-any
      for (const c of rows as any[]) xpEarnedByCharacterId[c.character_id] = PVP_XP_WIN;
    }
  }

  return { won, ratingDelta: attackerDelta, newRating, rewardCredits: won ? REWARD_CREDITS_WIN : REWARD_CREDITS_LOSS, xpEarnedByCharacterId };
}
