import {
  Swords,
  Users,
  IdCard,
  Store,
  Repeat,
  Hammer,
  Sparkles,
  Shield,
  Crosshair,
  MessageCircle,
  Orbit,
  Crown,
  Zap,
  Coins,
  Gem,
  User,
  Bell,
  Settings,
  BookOpen,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Play,
  RotateCcw,
  FlagOff,
  Globe,
  Megaphone,
  Terminal,
  Send,
  X,
  Lock,
  Map,
  Heart,
  Bug,
  Droplet,
  FlaskConical,
  ZapOff,
  TrendingDown,
  ShieldOff,
  Turtle,
  ImageOff,
  Star,
  Mail,
  Loader2,
  CheckCircle2,
  LogOut,
  Gauge,
  Wind,
  ScrollText,
  Gift,
  Package,
  ShoppingBag,
  Skull,
  Pencil,
  Plus,
  Binary,
  Unlock,
  ArrowUpCircle,
  Trophy,
  type LucideProps,
} from 'lucide-react';
import type { FC } from 'react';

const REGISTRY: Record<string, FC<LucideProps>> = {
  swords: Swords,
  users: Users,
  'id-card': IdCard,
  store: Store,
  repeat: Repeat,
  hammer: Hammer,
  sparkles: Sparkles,
  shield: Shield,
  crosshair: Crosshair,
  'message-circle': MessageCircle,
  orbit: Orbit,
  crown: Crown,
  zap: Zap,
  coins: Coins,
  gem: Gem,
  user: User,
  bell: Bell,
  settings: Settings,
  'book-open': BookOpen,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  play: Play,
  'rotate-ccw': RotateCcw,
  'flag-off': FlagOff,
  globe: Globe,
  megaphone: Megaphone,
  terminal: Terminal,
  send: Send,
  x: X,
  lock: Lock,
  map: Map,
  heart: Heart,
  bug: Bug,
  droplet: Droplet,
  'flask-conical': FlaskConical,
  'zap-off': ZapOff,
  'trending-down': TrendingDown,
  'shield-off': ShieldOff,
  turtle: Turtle,
  'image-off': ImageOff,
  star: Star,
  mail: Mail,
  loader: Loader2,
  'check-circle': CheckCircle2,
  'log-out': LogOut,
  gauge: Gauge,
  wind: Wind,
  'scroll-text': ScrollText,
  gift: Gift,
  package: Package,
  'shopping-bag': ShoppingBag,
  skull: Skull,
  pencil: Pencil,
  plus: Plus,
  binary: Binary,
  unlock: Unlock,
  'arrow-up-circle': ArrowUpCircle,
  trophy: Trophy,
};

interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const Cmp = REGISTRY[name];
  if (!Cmp) return null;
  return <Cmp {...props} />;
}
